/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package projetofinal;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author João Pedro
 */
public class PedidoForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form PedidoForm
     */
    public PedidoForm() {
        initComponents();
        this.setTitle("Pedido");
        this.setSize(340,310);
        this.setClosable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.setResizable(false);
        
        cbxCafe.setModel(new DefaultComboBoxModel());
        cbxCafe.addItem("Comum");
        cbxCafe.addItem("Duplo");
        cbxCafe.addItem("Espresso");
        cbxCafe.addItem("Descafeinado");
        
        cbxSanduiche.setModel(new DefaultComboBoxModel());
        cbxSanduiche.addItem("Misto Quente");
        cbxSanduiche.addItem("Pão na Chapa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCafe = new javax.swing.JLabel();
        cbxCafe = new javax.swing.JComboBox<>();
        txtSanduiche = new javax.swing.JLabel();
        cbxSanduiche = new javax.swing.JComboBox<>();
        lblQtdCafe = new javax.swing.JLabel();
        lblQtdSand = new javax.swing.JLabel();
        txtQtdCafé = new javax.swing.JTextField();
        txtQtdSand = new javax.swing.JTextField();
        lblMesa = new javax.swing.JLabel();
        txtMesa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        lblCafe.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblCafe.setText("Cafés");

        cbxCafe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtSanduiche.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtSanduiche.setText("Sanduíches");

        cbxSanduiche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblQtdCafe.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblQtdCafe.setText("Qntd.:");

        lblQtdSand.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblQtdSand.setText("Qntd.:");

        lblMesa.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lblMesa.setText("Mesa:");

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jButton1.setText("Pedir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbxSanduiche, 0, 150, Short.MAX_VALUE)
                            .addComponent(cbxCafe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCafe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSanduiche, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQtdCafe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdCafé, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQtdSand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdSand, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdCafe)
                    .addComponent(txtQtdCafé, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtSanduiche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxSanduiche, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdSand)
                            .addComponent(txtQtdSand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMesa))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StringBuilder sb = new StringBuilder();
        sb.append("Pedido Feito!").append("\n");
        sb.append("\nBebida:").append(txtQtdCafé.getText()).append("x ").append(cbxCafe.getSelectedItem());
        sb.append("\nSanduíche:").append(txtQtdSand.getText()).append("x ").append(cbxSanduiche.getSelectedItem());
        sb.append("\nMesa:").append(txtMesa.getText());
        
        JOptionPane.showMessageDialog(null, sb.toString());
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxCafe;
    private javax.swing.JComboBox<String> cbxSanduiche;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCafe;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblQtdCafe;
    private javax.swing.JLabel lblQtdSand;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtQtdCafé;
    private javax.swing.JTextField txtQtdSand;
    private javax.swing.JLabel txtSanduiche;
    // End of variables declaration//GEN-END:variables
}
