/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetofinal;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author João Pedro
 */
public class PrincipalForm extends javax.swing.JFrame {
    /**
     * Creates new form PrincipalForm
     */
    public PrincipalForm() {
        initComponents();
        this.setTitle("Principal");
        this.setSize(600,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        areaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpções = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenuItem();
        menuMesas = new javax.swing.JMenu();
        menuOcupação = new javax.swing.JMenuItem();
        menuReservar = new javax.swing.JMenuItem();
        menuProdutos = new javax.swing.JMenu();
        menuProntos = new javax.swing.JMenuItem();
        menuPedir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuConta = new javax.swing.JMenuItem();
        menuPagamento = new javax.swing.JMenuItem();

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );

        menuOpções.setText("Opções");
        menuOpções.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpçõesActionPerformed(evt);
            }
        });

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuOpções.add(menuSair);

        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuOpções.add(menuSobre);

        jMenuBar1.add(menuOpções);

        menuMesas.setText("Mesas");
        menuMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMesasActionPerformed(evt);
            }
        });

        menuOcupação.setText("Ocupação");
        menuOcupação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOcupaçãoActionPerformed(evt);
            }
        });
        menuMesas.add(menuOcupação);

        menuReservar.setText("Reservar");
        menuReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReservarActionPerformed(evt);
            }
        });
        menuMesas.add(menuReservar);

        jMenuBar1.add(menuMesas);

        menuProdutos.setText("Produtos");

        menuProntos.setText("Prontos");
        menuProntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProntosActionPerformed(evt);
            }
        });
        menuProdutos.add(menuProntos);

        menuPedir.setText("Pedir");
        menuPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPedirActionPerformed(evt);
            }
        });
        menuProdutos.add(menuPedir);

        jMenuBar1.add(menuProdutos);

        jMenu1.setText("Pendente");

        menuConta.setText("Conta");
        menuConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContaActionPerformed(evt);
            }
        });
        jMenu1.add(menuConta);

        menuPagamento.setText("Pagamento");
        menuPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPagamentoActionPerformed(evt);
            }
        });
        jMenu1.add(menuPagamento);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuOpçõesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpçõesActionPerformed
        
    }//GEN-LAST:event_menuOpçõesActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        abrirFormularioInterno(new SobreForm());
    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMesasActionPerformed

    private void menuContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContaActionPerformed
        abrirFormularioInterno (new ContaForm());
    }//GEN-LAST:event_menuContaActionPerformed

    private void menuOcupaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOcupaçãoActionPerformed
        abrirFormularioInterno (new OcupaçãoForm());
    }//GEN-LAST:event_menuOcupaçãoActionPerformed

    private void menuReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReservarActionPerformed
        abrirFormularioInterno (new ReservarForm());
    }//GEN-LAST:event_menuReservarActionPerformed

    private void menuProntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProntosActionPerformed
        abrirFormularioInterno (new ProntosForm());
    }//GEN-LAST:event_menuProntosActionPerformed

    private void menuPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPedirActionPerformed
        abrirFormularioInterno (new PedidoForm());
    }//GEN-LAST:event_menuPedirActionPerformed

    private void menuPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPagamentoActionPerformed
        
    }//GEN-LAST:event_menuPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem menuConta;
    private javax.swing.JMenu menuMesas;
    private javax.swing.JMenuItem menuOcupação;
    private javax.swing.JMenu menuOpções;
    private javax.swing.JMenuItem menuPagamento;
    private javax.swing.JMenuItem menuPedir;
    private javax.swing.JMenu menuProdutos;
    private javax.swing.JMenuItem menuProntos;
    private javax.swing.JMenuItem menuReservar;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSobre;
    // End of variables declaration//GEN-END:variables
    
    private void abrirFormularioInterno (JInternalFrame f) {
        
        if (areaTrabalho.getAllFrames().length ==0){
        areaTrabalho.add(f);
        f.setVisible(true);
        
        //Centralizar o Formulário Interno
        Dimension d = this.getSize();
        f.setLocation(
            (d.width-f.getSize().width)/2,
            (d.height-f.getSize().height)/2);
        } else {
            JOptionPane.showMessageDialog(null,
                    "A aplicação permite apenas uma janela aberta por vez");
        }
    } 
}
